# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lf608BsklOa3gL/pZ9mwPuqRkBEcgvNDrU/5AqMq2aAZ3EwwBYOjPjFfu8IzRR04hGZZ2iK1lVxYJBzmN2wUOGLGJV7o4eNEdwRpAosso1gJe/QD1L39pLyccUZ1tHn3UZY7qdIqS+QVm6U5Tn0KQmGFNGQvzdj7pj6NFpLr9KFd5mbzcnt+bHpjm61V4RMUX6a89bkOIGVpl82AN12PlsAkP6qKYfFgP4DFHTnssCwHqWcVo1hXcIIug/viLUYEx4aqLTh6LcJxFLfcv8RopuVXWaLKFwN6GsLd4gKkwLbVuzryURv+AE6G34O1MLuoB5HN01owPNVu5hwcYbm3r3zko2Og73BGaPGJnf7Lpwb1BdTj9LwW4HBfNGbF5TrEhjTnwe4acAuWO0Mn0rbjKlNkZmNLG3SkjRbiUMzg+JP9/stxrcVrO5isqnskl8Sv6FctrD7NOqQiPQCBfIudwLvYJOgeOveyCYQ8wNZxA8RloPh2Cxjtky24qePL21zK8xCByKBR16jeWmq3tt0SFmIsIkNCtLvEsr2U90SUWG0Ztcf0YgQoKsdTwbPzyRxaOXqUfs/53/nCQ+V7ukiPlneto24rCkpqFX3TfDbee6tKwW4pWHKcuLbLi+689Boa+YCDUgEGtqvQcp8klwnVWgQyqcuOkydzPdryg82fzLc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
