travis:
  secure:
    BINSTAR_TOKEN: lf608BsklOa3gL/pZ9mwPuqRkBEcgvNDrU/5AqMq2aAZ3EwwBYOjPjFfu8IzRR04hGZZ2iK1lVxYJBzmN2wUOGLGJV7o4eNEdwRpAosso1gJe/QD1L39pLyccUZ1tHn3UZY7qdIqS+QVm6U5Tn0KQmGFNGQvzdj7pj6NFpLr9KFd5mbzcnt+bHpjm61V4RMUX6a89bkOIGVpl82AN12PlsAkP6qKYfFgP4DFHTnssCwHqWcVo1hXcIIug/viLUYEx4aqLTh6LcJxFLfcv8RopuVXWaLKFwN6GsLd4gKkwLbVuzryURv+AE6G34O1MLuoB5HN01owPNVu5hwcYbm3r3zko2Og73BGaPGJnf7Lpwb1BdTj9LwW4HBfNGbF5TrEhjTnwe4acAuWO0Mn0rbjKlNkZmNLG3SkjRbiUMzg+JP9/stxrcVrO5isqnskl8Sv6FctrD7NOqQiPQCBfIudwLvYJOgeOveyCYQ8wNZxA8RloPh2Cxjtky24qePL21zK8xCByKBR16jeWmq3tt0SFmIsIkNCtLvEsr2U90SUWG0Ztcf0YgQoKsdTwbPzyRxaOXqUfs/53/nCQ+V7ukiPlneto24rCkpqFX3TfDbee6tKwW4pWHKcuLbLi+689Boa+YCDUgEGtqvQcp8klwnVWgQyqcuOkydzPdryg82fzLc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
